=== saeidvn/gym_parser_homework/src/main/resources/gym.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="gym" type="gymType">
    <xs:annotation>
      <xs:documentation>&lt;main-tag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:////home/sa/IdeaProjects/gym/src/main/resources/gym.xsd"></xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="memberType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Bob"/>
            <xs:enumeration value="Sara"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="yogaInstrumentType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="type"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="yogaTrainerType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="dateOfBirth"/>
      <xs:element type="xs:string" name="yogaPant"/>
      <xs:element type="yogaInstrumentType" name="yogaInstrument"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="trainerType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="dateOfBirth"/>
      <xs:element type="xs:string" name="type"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="trainersType">
    <xs:sequence>
      <xs:element type="yogaTrainerType" name="yogaTrainer"/>
      <xs:element type="trainerType" name="trainer"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gymType">
    <xs:sequence>
      <xs:element type="memberType" name="member" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="trainersType" name="trainers"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== saeidvn/gym_parser_homework/target/classes/gym.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<!--        xsi:noNamespaceSchemaLocation="gym.xsd"-->

<gym>
    <members>
        <member id="1">
            <name>Bob</name>
        </member>
        <member id="2">
            <name>Sara</name>
        </member>
    </members>
    <trainers>
        <yogaTrainer>
            <name>Anna</name>
            <dateOfBirth>1980-04-20</dateOfBirth>
            <yogaPant>WORKOUT</yogaPant>
            <yogaInstrument>
                <name>drum</name>
                <type>DRUM</type>
            </yogaInstrument>
        </yogaTrainer>
        <trainer>
            <name>Mike</name>
            <dateOfBirth>1980-04-20</dateOfBirth>
            <type>Box</type>
        </trainer>
    </trainers>
</gym>
